#pragma once

#define WIDTH 1920
#define HEIGHT 1080

#define PLAYER_ROT_DEG 25.0f
#define PLAYER_BASE_WIDTH 35
#define PLAYER_TRI_HEIGHT 50
#define PLAYER_VEL_X 10.0f
#define PLAYER_VEL_Y 10.0f
#define PLYAER_MAX_SPEED 20.0f
#define PLAYER_SPEED 1.0f
#define PLAYER_LIVES 3

#define MAX_ASTROID_RADIUS 40.0f
#define NO_OF_POINTS_IN_ASTROID 8
#define ASTROID_SPEED 2.0f
#define ASTROIDS_POOL_SIZE 100
#define ASTROIDS_SIZE 35

#define BULLET_POOL_SIZE 100
#define BULLET_SIZE 10
#define BULLET_X_SPEED 5.0f
#define BULLET_Y_SPEED 5.0f
